# Generated by Django 5.0.2 on 2024-03-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emmail',
            new_name='email',
        ),
    ]
